# Generated by Django 3.1.2 on 2020-10-07 11:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0003_auto_20201007_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='author',
            field=models.ForeignKey(on_delete=models.Model, related_name='products', to=settings.AUTH_USER_MODEL),
        ),
    ]
