# Generated by Django 3.1.2 on 2020-10-08 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20201007_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='gender',
            field=models.CharField(choices=[('men', 'men'), ('women', 'women')], default='men', max_length=30),
        ),
    ]
