# Generated by Django 3.1.2 on 2020-10-08 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_productmodel_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='gender',
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='category',
            field=models.CharField(choices=[('men', 'men'), ('women', 'women')], default='---', max_length=100),
        ),
    ]
