# Generated by Django 3.1.2 on 2020-10-12 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20201008_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentmodel',
            name='product',
            field=models.ForeignKey(default=0, on_delete=models.Model, to='shop.productmodel'),
        ),
    ]
