# Generated by Django 3.1.2 on 2020-10-13 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_commentmodel_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentmodel',
            name='product',
            field=models.ForeignKey(default=1, on_delete=models.Model, to='shop.productmodel'),
        ),
    ]
